### Base URL
http://microbloglite.us-east-2.elasticbeanstalk.com

### Step 1) Register or create new user
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Content-Type: application/json

{
  "username": "Pooja",
  "fullName": "Pooja G",
  "password": "abc123"
}


### Step 2) Login
POST http://microbloglite.us-east-2.elasticbeanstalk.com/auth/login
Content-Type: application/json

{
  "username": "Pooja",
  "password": "abc123"
}


### Step 3) GET Users
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE5NDk3NjU0LCJleHAiOjE3MTk1ODQwNTR9.gl2u8IqwoRyGnW4sOw4d3gJGJSHbCRp4B5mzOKjxNLM



### Step 4) GET One User
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/Pooja
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE5NDk3NjU0LCJleHAiOjE3MTk1ODQwNTR9.gl2u8IqwoRyGnW4sOw4d3gJGJSHbCRp4B5mzOKjxNLM


### Step 5) Create a Post
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE4OTgzNjA4LCJleHAiOjE3MTkwNzAwMDh9.-WXmKbO3WW8wQlgf0pkCkYsd00altfg3JECe9UqLkDU

{
  "text": "Hello World"
}

### Step 6) GET Posts
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE4OTgzNjA4LCJleHAiOjE3MTkwNzAwMDh9.-WXmKbO3WW8wQlgf0pkCkYsd00altfg3JECe9UqLkDU

# 6675a16ffbf13c2cc0eaf70a

### Step 6b) GET Posts
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a16ffbf13c2cc0eaf70a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE4OTgzNjA4LCJleHAiOjE3MTkwNzAwMDh9.-WXmKbO3WW8wQlgf0pkCkYsd00altfg3JECe9UqLkDU

# 6675a16ffbf13c2cc0eaf70a

### Step 7) DELETE Post
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a16ffbf13c2cc0eaf70a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE4OTgzNjA4LCJleHAiOjE3MTkwNzAwMDh9.-WXmKbO3WW8wQlgf0pkCkYsd00altfg3JECe9UqLkDU

### Step 8) Update User
PUT http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/Pooja
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE4OTgzNjA4LCJleHAiOjE3MTkwNzAwMDh9.-WXmKbO3WW8wQlgf0pkCkYsd00altfg3JECe9UqLkDU

{
  "fullName": "PoojaG",
  "Bio": "ABC"
}


### Step 9) Add Like
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE4OTgzNjA4LCJleHAiOjE3MTkwNzAwMDh9.-WXmKbO3WW8wQlgf0pkCkYsd00altfg3JECe9UqLkDU

{
  "postId": "6675a16ffbf13c2cc0eaf70a"
}

### Step 10) Delete/Remove Like
DELETE  http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes/6675a16ffbf13c2cc0eaf70a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBvb2phIiwiaWF0IjoxNzE4OTgzNjA4LCJleHAiOjE3MTkwNzAwMDh9.-WXmKbO3WW8wQlgf0pkCkYsd00altfg3JECe9UqLkDU
